language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t alfalconer/Brightsites-app -f Dockerfile.dev .

script:
  - docker run -e CI=true alfalconer/Brightsites-app npm run test

after_success:
  - docker build -t alfalconer/Brightsites-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alfalconer/Brightsites-app